import type { Paper } from './types';

/** Mock papers for frontend testing without Tauri backend */
export const mockPapers: Paper[] = [
  {
    id: 'paper-001',
    title: '基于深度学习的自然语言处理方法研究',
    authors: '["张三", "李四", "王五"]',
    year: 2024,
    journal: '计算机学报',
    doi: '10.1234/comp.2024.001',
    url: null,
    abstract_text: '本文综述了基于深度学习的自然语言处理方法...',
    keywords: '["深度学习", "NLP", "Transformer"]',
    citation_key: 'zhang2024deep',
    bibtex: null,
    file_path: '/tmp/test.pdf',
    file_size: 2048576,
    page_count: 12,
    language: 'zh',
    created_at: '2026-06-15T10:00:00Z',
    updated_at: '2026-06-15T10:00:00Z',
    item_type: 'journal',
    volume: null,
    issue: null,
    pages: null,
    conference_name: null,
    publisher: null,
    place: null,
    editor: '[]',
    series: null,
    edition: null,
    isbn: null,
    issn: null,
    num_pages: null,
    archive_location: null,
    call_number: null,
    rights: null,
    deleted_at: null,
    is_favorite: 0,
    read_status: 'unread',
    last_read_at: null,
    imported_at: '2026-06-15T10:00:00Z',
  },
  {
    id: 'paper-002',
    title: 'Attention Is All You Need',
    authors: '["Ashish Vaswani", "Noam Shazeer", "Niki Parmar"]',
    year: 2017,
    journal: 'NeurIPS',
    doi: '10.1234/neurips.2017.002',
    url: null,
    abstract_text: 'The dominant sequence transduction models are based on...',
    keywords: '["attention", "transformer", "deep learning"]',
    citation_key: 'vaswani2017attention',
    bibtex: null,
    file_path: '/tmp/test2.pdf',
    file_size: 1048576,
    page_count: 15,
    language: 'en',
    created_at: '2026-06-16T08:00:00Z',
    updated_at: '2026-06-16T08:00:00Z',
    item_type: 'journal',
    volume: null,
    issue: null,
    pages: null,
    conference_name: null,
    publisher: null,
    place: null,
    editor: '[]',
    series: null,
    edition: null,
    isbn: null,
    issn: null,
    num_pages: null,
    archive_location: null,
    call_number: null,
    rights: null,
    deleted_at: null,
    is_favorite: 1,
    read_status: 'read',
    last_read_at: '2026-06-16T08:00:00Z',
    imported_at: '2026-06-16T08:00:00Z',
  },
  {
    id: 'paper-003',
    title: 'A Survey of Large Language Models',
    authors: '["Wayne Xin Zhao"]',
    year: 2023,
    journal: 'arXiv',
    doi: null,
    url: 'https://arxiv.org/abs/2303.18223',
    abstract_text: 'Large language models have become a hot research topic...',
    keywords: '["LLM", "survey", "GPT"]',
    citation_key: 'zhao2023survey',
    bibtex: null,
    file_path: null,
    file_size: null,
    page_count: 45,
    language: 'en',
    created_at: '2026-06-16T09:00:00Z',
    updated_at: '2026-06-16T09:00:00Z',
    item_type: 'journal',
    volume: null,
    issue: null,
    pages: null,
    conference_name: null,
    publisher: null,
    place: null,
    editor: '[]',
    series: null,
    edition: null,
    isbn: null,
    issn: null,
    num_pages: null,
    archive_location: null,
    call_number: null,
    rights: null,
    deleted_at: null,
    is_favorite: 0,
    read_status: 'unread',
    last_read_at: null,
    imported_at: '2026-06-16T09:00:00Z',
  },
];
