//! End-to-end encryption for sync payloads (AES-256-GCM).
//!
//! The sync key is generated by the host during pairing and distributed to the
//! guest through the (controlled) pairing channel. The relay only ever stores
//! ciphertext.

use aes_gcm::aead::{Aead, KeyInit};
use aes_gcm::{Aes256Gcm, Nonce};
use rand::RngCore;

pub const SYNC_KEY_LEN: usize = 32;
pub const NONCE_LEN: usize = 12;

/// Generate a fresh 256-bit sync key.
#[allow(dead_code)] // exercised by tests; production keys come from the server
pub fn generate_sync_key() -> [u8; SYNC_KEY_LEN] {
    let mut key = [0u8; SYNC_KEY_LEN];
    rand::thread_rng().fill_bytes(&mut key);
    key
}

/// Encrypt `plaintext` with `key`, returning `(ciphertext, nonce)`. A fresh
/// random nonce is used for every call.
pub fn encrypt_bytes(
    key: &[u8; SYNC_KEY_LEN],
    plaintext: &[u8],
) -> Result<(Vec<u8>, [u8; NONCE_LEN]), String> {
    let cipher = Aes256Gcm::new_from_slice(key).map_err(|e| format!("key init: {e}"))?;
    let mut nonce = [0u8; NONCE_LEN];
    rand::thread_rng().fill_bytes(&mut nonce);
    let ciphertext = cipher
        .encrypt(Nonce::from_slice(&nonce), plaintext)
        .map_err(|e| format!("encrypt failed: {e}"))?;
    Ok((ciphertext, nonce))
}

/// Decrypt `ciphertext` produced by `encrypt_bytes`. Returns Err on a wrong
/// key, a tampered payload, or a malformed nonce.
pub fn decrypt_bytes(
    key: &[u8; SYNC_KEY_LEN],
    nonce: &[u8],
    ciphertext: &[u8],
) -> Result<Vec<u8>, String> {
    if nonce.len() != NONCE_LEN {
        return Err(format!("bad nonce length {}", nonce.len()));
    }
    let cipher = Aes256Gcm::new_from_slice(key).map_err(|e| format!("key init: {e}"))?;
    cipher
        .decrypt(Nonce::from_slice(nonce), ciphertext)
        .map_err(|_| "decrypt failed (wrong key or tampered payload)".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trip() {
        let key = generate_sync_key();
        let (ct, nonce) = encrypt_bytes(&key, b"hello sync").unwrap();
        let pt = decrypt_bytes(&key, &nonce, &ct).unwrap();
        assert_eq!(pt, b"hello sync");
    }

    #[test]
    fn wrong_key_fails() {
        let key = generate_sync_key();
        let other = generate_sync_key();
        let (ct, nonce) = encrypt_bytes(&key, b"secret").unwrap();
        assert!(decrypt_bytes(&other, &nonce, &ct).is_err());
    }

    #[test]
    fn tampered_ciphertext_fails() {
        let key = generate_sync_key();
        let (mut ct, nonce) = encrypt_bytes(&key, b"secret").unwrap();
        let last = ct.len() - 1;
        ct[last] ^= 0x01;
        assert!(decrypt_bytes(&key, &nonce, &ct).is_err());
    }
}
